Milestone4/logic
YoseptF/react-calculator pull request #4
Opened 2020-06-03 15:09 UTC by YoseptF

I added the logic to run the calculator
- The operator module uses big.js to run math operations
- The calculate module uses operator to modify the state of the application

I also modified some of the existing logic in the app to make it easier to use these 2 new modules.

2020-06-04 09:30 UTC, bellom requested changes
## Hi @YoseptF  :clap: 

### Awesome job so far!! :+1: 

**NOTE: kindly fix the linter's error**
fix all errors:** checkout this [linters-config#troubleshooting](https://github.com/microverseinc/linters-config#troubleshooting) for help. Example below;
![image](https://user-images.githubusercontent.com/31897434/63073279-0e393680-bf20-11e9-9c84-f142caf1e675.png)
#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-06-04 09:30 UTC, bellom commented on src/logic/operate.js
> +      return bigOne - bigTwo;
Good job getting this far.
The way you used the new `big.js` I am curious about it.
kindly check out what we have on the doc.
`https://mikemcl.github.io/big.js/`
Example:
`bigOne.minus(bigTwo)`

2020-06-04 09:30 UTC, bellom commented on src/logic/operate.js
> +      return bigOne % bigTwo;
Note: case `%` require just the first digit which is `bigOne`

2020-06-04 09:30 UTC, bellom commented on src/logic/calculate.js
> +  return newData;
we need to add more conditions, like;
1. division zero error handling(if we divide a digit by zero we should get an error message)
2. when `.` return `0.`

2020-06-05 16:46 UTC, AdnanAfsari approved these changes
**Status: Approved**

Hello @YoseptF ✋ 

Nice work, You have made changes requested by the previous reviewer.It's a 👍 .

Happy Coding
Adnan Afsari

2020-07-06 16:04 UTC, merged